apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./all.yaml

patches:
  - path: ./patch-kustomize-guestbook.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: kustomize-guestbook
